//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamScore { get; set; }
        public int ResultID { get; set; }
        public string Result { get; set; }
        public System.DateTime WeekDate { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
